### ISSUE TITLE
invite workflow is disabled

### ISSUE THREAD

**Issue by shogo82148** [reviewdog/inviter#23]
https://github.com/reviewdog/inviter/actions/workflows/invite.yml is disable and not working now.

![image](https://user-images.githubusercontent.com/1157344/126634879-96def012-9c4d-41a2-bead-b85c186e017c.png)

Can someone enable it, or give me a permission to enable it ?

**Comment by haya14busa** [comment]
I added @reviewdog/maintainers as a maintainer role.

**Comment by shogo82148** [comment]
Thanks!
I'm now able to run the workflow.
